spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456  
  java:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


logging:
  level: 
    org:
      hibernate: 
        SQL: DEBUG
        ORM: 
          JDBC:
            bind: TRACE


kafka:
  topics:
    product-created: product.created
    product-updated: product.updated
