spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456  

