
server:
  port: 8386

spring:
  application:
    name: auth-service

keycloak:
  server-url: http://localhost:8181
  realm: ecommerce-project
  client-id: backend
  credentials:
    secret: 'kk4iyY7jcYexwxf3YddNZYGhHrMm8WM2'
  token-uri: ${keycloak.server-url}/realms/ecommerce-project/protocol/openid-connect/token
  admin-uri: ${server-url}/admin/realms/${keycloak.realm}


